require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 100

Naming/FileName:
  Exclude:
    - 'lib/omniauth-docusign.rb'

RSpec/FilePath:
  Enabled: false
  # This should work, but explodes
  # CustomTransform:
  #   - OmniAuth: "omniauth"

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - 'Guardfile'
